name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch name

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Deploy the entire repository
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
